title: osu!std Korean Mapping Guide
description: zz

# GitHub Pages용 테마 설정
remote_theme: just-the-docs/just-the-docs

url: "https://unlimitosu.github.io"
baseurl: "" # 메인 페이지로 사용 시 비워둡니다.

permalink: pretty

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y"

# [중요] 레이아웃 기본값 설정 (들여쓰기 수정됨)
defaults:
  - scope:
      path: "" # 모든 파일에 기본 레이아웃 적용
    values:
      layout: "default"

# 빌드 제외 파일
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile

# 검색 및 기능 설정
search_enabled: true
enable_copy_code_button: true
heading_anchors: true
nav_enabled: true
color_scheme: dark

# [중요] 플러그인 목록 (remote-theme 필수 포함)
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-remote-theme

# Sass 설정
sass:
  quiet_deps: true
  silence_deprecations: ['import']

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: green
  warning:
    title: Warning
    color: red


callouts_level: quiet

kramdown:
  input: GFM        # GitHub Flavored Markdown 사용
  syntax_highlighter_opts:
    block:
      line_numbers: false